import React, { useState } from 'react';
import { QuizQuestion } from '../types';
import { generateQuizQuestion } from '../services/geminiService';
import { Brain, CheckCircle, XCircle, ChevronRight, Play, GraduationCap, Loader2 } from 'lucide-react';

export const Quiz: React.FC<{ isDarkMode?: boolean }> = ({ isDarkMode }) => {
  const [currentQuestion, setCurrentQuestion] = useState<QuizQuestion | null>(null);
  const [selectedOption, setSelectedOption] = useState<number | null>(null);
  const [showExplanation, setShowExplanation] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [topic, setTopic] = useState('Well Control Principles');

  const topics = [
    'Well Control Principles',
    'Kill Sheets',
    'BOP Equipment',
    'Kick Detection',
    'Fracture Gradient',
    'Stripping Operations'
  ];

  const handleStartQuiz = async () => {
    setIsLoading(true);
    setSelectedOption(null);
    setShowExplanation(false);
    
    const question = await generateQuizQuestion(topic);
    setCurrentQuestion(question);
    setIsLoading(false);
  };

  const handleSelectOption = (index: number) => {
    if (showExplanation) return;
    setSelectedOption(index);
    setShowExplanation(true);
  };

  return (
    <div className={`h-full flex flex-col items-center justify-center p-12 transition-colors duration-700 ${isDarkMode ? 'bg-[#020617]' : 'bg-slate-50/50'}`}>
      {!currentQuestion && !isLoading ? (
        <div className={`p-16 rounded-[3.5rem] shadow-2xl border text-center max-w-xl w-full transition-all duration-700 ${isDarkMode ? 'bg-[#0f172a] border-white/5' : 'bg-white border-slate-200'}`}>
          <div className="w-24 h-24 bg-blue-600 rounded-3xl flex items-center justify-center mx-auto mb-10 shadow-2xl shadow-blue-900/40">
            <GraduationCap className="h-12 w-12 text-white" />
          </div>
          <h2 className={`text-4xl font-black tracking-tighter uppercase mb-4 ${isDarkMode ? 'text-white' : 'text-slate-900'}`}>Knowledge Assessment</h2>
          <p className="text-slate-500 mb-12 text-lg font-medium leading-relaxed">Test your technical precision with IWCF-standard scenarios generated by WellTegra AI.</p>
          
          <div className="text-left mb-10">
            <label className="block text-[10px] font-black text-slate-500 uppercase tracking-[0.3em] mb-4 font-mono">Select Technical Domain</label>
            <div className="relative">
              <select 
                value={topic}
                onChange={(e) => setTopic(e.target.value)}
                className={`w-full appearance-none rounded-2xl px-6 py-5 outline-none font-bold text-sm border transition-all ${
                  isDarkMode ? 'bg-white/5 border-white/10 text-white focus:border-blue-500' : 'bg-slate-50 border-slate-200 text-slate-900 focus:border-blue-600'
                }`}
              >
                {topics.map(t => <option key={t} value={t}>{t}</option>)}
              </select>
              <ChevronRight className="absolute right-6 top-1/2 -translate-y-1/2 rotate-90 text-slate-400" size={18} />
            </div>
          </div>

          <button 
            onClick={handleStartQuiz}
            className="w-full bg-blue-600 hover:bg-blue-700 text-white font-black py-6 rounded-[1.75rem] transition-all flex items-center justify-center gap-4 text-[12px] uppercase tracking-[0.3em] shadow-2xl shadow-blue-900/50 active:scale-95"
          >
            <Play size={20} /> Initialize Assessment
          </button>
        </div>
      ) : isLoading ? (
        <div className="text-center">
          <div className="relative w-20 h-20 mx-auto mb-8">
            <Loader2 className="h-20 w-20 text-blue-600 animate-spin opacity-20" />
            <Brain className="absolute inset-0 m-auto h-8 w-8 text-blue-600 animate-pulse" />
          </div>
          <p className="text-slate-500 font-black text-[12px] uppercase tracking-[0.4em] animate-pulse">Consulting technical knowledge matrix...</p>
        </div>
      ) : currentQuestion ? (
        <div className={`rounded-[3.5rem] shadow-2xl border max-w-3xl w-full overflow-hidden transition-all duration-700 ${isDarkMode ? 'bg-[#0f172a] border-white/5' : 'bg-white border-slate-200'}`}>
          <div className="p-16">
            <div className="flex items-center gap-4 mb-10">
              <span className="bg-blue-600 text-white text-[10px] font-black px-4 py-1.5 rounded-full uppercase tracking-widest">Active Scenario</span>
              <span className="text-slate-500 text-[10px] font-black uppercase tracking-widest font-mono">{topic}</span>
            </div>
            
            <h3 className={`text-3xl font-black tracking-tight leading-tight mb-12 ${isDarkMode ? 'text-white' : 'text-slate-900'}`}>
              {currentQuestion.question}
            </h3>

            <div className="space-y-4">
              {currentQuestion.options.map((option, idx) => {
                let stateClass = isDarkMode ? "border-white/5 hover:bg-white/[0.03]" : "border-slate-100 hover:bg-slate-50";
                let Icon = null;

                if (showExplanation) {
                  if (idx === currentQuestion.correctIndex) {
                    stateClass = isDarkMode ? "bg-emerald-500/10 border-emerald-500/50 ring-1 ring-emerald-500" : "bg-emerald-50 border-emerald-200 ring-1 ring-emerald-500";
                    Icon = CheckCircle;
                  } else if (idx === selectedOption) {
                    stateClass = isDarkMode ? "bg-rose-500/10 border-rose-500/50 ring-1 ring-rose-500" : "bg-rose-50 border-rose-200 ring-1 ring-rose-500";
                    Icon = XCircle;
                  } else {
                    stateClass = "opacity-30 border-transparent";
                  }
                } else if (idx === selectedOption) {
                    stateClass = "bg-blue-500/10 border-blue-500 ring-1 ring-blue-500";
                }

                return (
                  <button
                    key={idx}
                    onClick={() => handleSelectOption(idx)}
                    disabled={showExplanation}
                    className={`w-full text-left p-6 rounded-[1.75rem] border-2 transition-all flex items-center justify-between group ${stateClass}`}
                  >
                    <span className={`font-bold text-sm ${showExplanation && idx === currentQuestion.correctIndex ? (isDarkMode ? 'text-emerald-400' : 'text-emerald-800') : (isDarkMode ? 'text-slate-300' : 'text-slate-700')}`}>
                      {option}
                    </span>
                    {Icon && <Icon size={20} className={idx === currentQuestion.correctIndex ? 'text-emerald-500' : 'text-rose-500'} />}
                  </button>
                );
              })}
            </div>

            {showExplanation && (
              <div className={`mt-12 rounded-[2.5rem] p-10 border animate-in fade-in slide-in-from-bottom-4 duration-700 ${isDarkMode ? 'bg-white/[0.03] border-white/5' : 'bg-slate-50 border-slate-200'}`}>
                <h4 className={`font-black text-[11px] uppercase tracking-[0.3em] mb-4 flex items-center gap-3 ${isDarkMode ? 'text-blue-400' : 'text-blue-600'}`}>
                   Technical Briefing
                </h4>
                <p className={`text-sm leading-relaxed font-medium mb-8 ${isDarkMode ? 'text-slate-400' : 'text-slate-600'}`}>
                  {currentQuestion.explanation}
                </p>
                <button 
                  onClick={handleStartQuiz}
                  className="w-full bg-slate-900 text-white dark:bg-white dark:text-slate-900 py-5 rounded-[1.5rem] font-black uppercase text-[10px] tracking-widest flex items-center justify-center gap-3 hover:opacity-90 transition-opacity"
                >
                  Proceed to Next Question <ChevronRight size={16} />
                </button>
              </div>
            )}
          </div>
        </div>
      ) : null}
    </div>
  );
};